# Generated by Django 4.0.1 on 2022-01-15 14:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Название')),
                ('article', models.CharField(max_length=20, null=True, verbose_name='Артикул')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание товара')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация о товаре')),
                ('purpose', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Назначение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/full', verbose_name='Большое изображение')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='item/thumb', verbose_name='Маленькое изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ?')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0, verbose_name='Объем')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('left', models.IntegerField(default=0, verbose_name='Остаток')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='Item.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=0, verbose_name='Название')),
                ('link', models.TextField(default=0, verbose_name='Код видео на youtube')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Item.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(default=0, verbose_name='Отзыв от')),
                ('text', models.TextField(default=0, verbose_name='Текст')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Item.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default=0, verbose_name='Вопрос')),
                ('answer', models.TextField(default=0, verbose_name='Ответ')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Item.item')),
            ],
        ),
    ]
