# Generated by Django 4.0.5 on 2022-07-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_itemvolume_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvolume',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Высота в см'),
        ),
        migrations.AddField(
            model_name='itemvolume',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Длина в см'),
        ),
        migrations.AddField(
            model_name='itemvolume',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Вес в кг'),
        ),
        migrations.AddField(
            model_name='itemvolume',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ширина в см'),
        ),
    ]
