# Generated by Django 4.0.1 on 2022-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Баннер')),
                ('image_mob', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Баннер мобильный')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.ImageField(blank=True, null=True, upload_to='form', verbose_name='Баннер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
