# Generated by Django 4.0.5 on 2022-06-28 10:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='blog', verbose_name='Картинка категории')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категории блога',
                'verbose_name_plural': 'Категории блога',
            },
        ),
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='blog', verbose_name='Картинка статьи')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название статьи')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст превью')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст полный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
