# Generated by Django 4.0.5 on 2022-07-04 06:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_blogcategory_blogitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogitem',
            old_name='full_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='blogitem',
            name='short_text',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст превью'),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='image_top',
            field=models.ImageField(null=True, upload_to='blog', verbose_name='Картинка в шапке статьи'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='image',
            field=models.ImageField(null=True, upload_to='blog', verbose_name='Картинка превью'),
        ),
    ]
