# Generated by Django 4.0.5 on 2022-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_full_text_blogitem_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
