# Generated by Django 4.0.5 on 2022-07-20 17:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_blogitem_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Условия оплаты')),
                ('delivery_info', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Условия доставки')),
                ('return_info', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Условия возврата')),
                ('contact_info', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Статические страницы',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
